export const ROUTES = {
  login: "/login",
  locations: "/locations",
  bookings: "/bookings",
  profile: "/profile",
  History: "/history",
  adminDashboard: "/admin/dashboard",
  adminLocations: "/admin/locations",
  adminLocationNew: "/admin/locations/new",
  adminLocationDetail: (id: string) => `/admin/locations/${id}`,
  adminLocationDetailEdit: (id: string) => `/admin/locations/${id}/edit`,
  adminBookings: "/admin/bookings",
  adminBookingDetail: (id: string) => `/admin/bookings/${id}`,
  adminUsers: "/admin/users",
  adminUserDetail: (id: string) => `/admin/users/${id}`,
} as const;
